name: Run Rest Assured Test Tests

on:
  push:
    branches: ["main" , "story-*"]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          cache: "maven"
          distribution: 'temurin'
      - run: mvn clean test